[package]
description = "CI script for Bevy"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "ci"
publish     = false
version     = "0.1.0"

[dependencies]
bitflags = "1"
xshell   = "0.2"
